$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: diabetes

model: azureml:diabetes-model-name:latest

environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:latest
  conda_file: conda.yml

code_configuration:
  code: ./src
  scoring_script: score.py

instance_type: Standard_DS3_v2
instance_count: 1
